---
- hosts: 10.4.0.5
  become: yes
  tasks:
  - include_taks: myfile.yml

  - name: i want to create folder
    file: 
      path: /home/rajuammu/myfolder
      state: directory

  - name: i want to copy file
    copy:
      src: mystaticfile
      dest: /home/rajuammu/ 
 
  - name: i want to install wget
    apt:
      name: wget
      state: present