---
- hosts: all
  become: yes
  tasks:
  - name: install apache2 for remove
    apt:
      name: apache2
      state: absent


  - name: uninstall git 
    apt:
      name: git 
      state: absent

  - name: uninstall wget
    apt:
      name: wget
      state: absent      