---
- hosts: 10.4.0.5
  become: yes
  tasks:
  - name: Copy file with owner and permissions
    copy:
      src: mystaticfile
      dest: /home/rajuammu/mynewfolder


  - name: apache2install
    apt:
      name: apache2
      state: present    

    
  - name: i want copy index file into node
    template:
      src: index.j2
      dest: /var/www/html/index.html

  - name: download from git 
    get_url:
      url: https://github.com/RajuVM9542/Anisble_Devops/blob/main/myfirstplaybook.yml 
      dest: /home/rajuammu/mynew
      force_basic_auth: yes
