---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: install apache2 for remove
    apt:
      name: apache2
      state: present
      when: ansible_os_family=="Debian"


  - name: uninstall git 
    apt:
      name: git 
      state: present
      when: ansible_os_family=="Debian"

  - name: uninstall wget
    apt:
      name: wget
      state: present 
      when: ansible_os_family=="Debian"     