---
- hosts: 10.4.0.4
  become: yes
  tasks:
  - include_taks: myfile.yml
  - name: i want to create folder
    file: 
      path: /home/rajuammu/myfolder
      state: directory

  - name: Copy file 
    ansible.builtin.copy:
      src: mystaticfile
      dest: /home/rajuammu/newfolder
 
  - name: i want to install wget
    apt:
      name: wget
      state: present


  - name: i want to install apache2
    apt:
      name: apache2
      state: present    

