---
- hosts: 10.4.0.5
  become: yes
  tasks:
  - name: Copy file with owner and permissions
    copy:
      src: mystaticfile
      dest: /home/rajuammu/mynewfolder


  - name: apache2install
    apt:
      name: apache2
      state: present    

    

    
