---
- hosts: 10.4.0.5
  become: yes
  vars:
     var01: git 
     var02: tree
     var03: wget
  tasks:
  
  - name: install git on 10.4.0.5 node
    apt:    
      name: "{{myjavapackonubuntu}}"
      state: absent 


  - name: install git on 10.4.0.5 node
    debug:
      msg: "{{myjavapackonubuntu}}"    